language: csharp
mono: none
dotnet: 2.1
script:
- dotnet build --configuration Release

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
  - ShellScript/bin/Release/netcoreapp2.1/ShellScript.dll
  - ShellScript/bin/Release/netcoreapp2.1/ShellScript.deps.json
  - ShellScript/bin/Release/netcoreapp2.1/ShellScript.runtimeconfig.dev.json
  - ShellScript/bin/Release/netcoreapp2.1/ShellScript.runtimeconfig.json
  - ShellScript/bin/Release/netcoreapp2.1/shellscript.shellscript
  - ShellScript/bin/Release/netcoreapp2.1/shellscript.sh

    skip_cleanup: true
  on:
    repo: amkherad/ShellScript
    tags: true
