language: csharp
mono: none
dotnet: 2.1
script:
- dotnet build --configuration Release
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: ShellScript/bin/Release/netcoreapp2.1/ShellScript.dll
  skip_cleanup: true
  on:
    repo: amkherad/ShellScript
