language: csharp
mono: none
dotnet: 2.1
script:
- dotnet build --configuration Release
deploy:
  provider: releases
  api_key:
    secure: Dm6g9LMH4BCEBIR+VReqHn+zuuuy1JZxkCy29Ln9L2UGLH0cerAKNdtuNwMQ7PI/I6KbWKKMje2tWg5Xt57HfFKqNcR1nztWRaCp+QQs9kE8mJpu8UwdtfztvzAefR10OyY7fvmkKdfypHHBgonWQSPuqajHzolzyql3TTgHZbZec0LbPIToJWiYXhVyE/aNm/AP6v4tALNVCry/8Qrv8EcYKw+t0L+m65CxeBI8i4iARt6mTh/GVO/mGw1CDcaJtrSADIylGvt3/Auj8W8/xP4C9Vsh0oxC87kbpPNI54JLUd1qlT8p2hQp16mIZrXbBZe7soZgyolar6I6VEcui58kFsc+Qip8MKl9PEJHlfF7DptcOzsfhMs1QCIOYBtluU4JOnosrnT+aAIVc4qXsmGcmk1bm12BTv0/kxgI5PF3JnFfIA82gJBBwIbNMRXEJrOG4uqpcd79T/dwCp0TvrOoQhal0dK1B511uWBKXrc1QJC5c030bLn5kZLcgVYI6E/wLrklhXehDb+yogWP8A5ny9FH5+JkAlD1mYvpAgl2H8sb1RevwJAb2ZOMr85UM6QHocxMARs1CoGxjnyjWIBZID4EgEStDlCIrCU7XSPbGyqlY6Qozl+h0+TE7xDlo1k8H6VEbt+YkvGAmiXenq4IiKSpmUEr6NnpzM6wFRs=
  file: ShellScript/bin/Release/netcoreapp2.1/ShellScript.dll
  skip_cleanup: true
  on:
    repo: amkherad/ShellScript
